#! /bin/sh

#!/bin/sh
echo this file is not meant for general distibution, but is used by the
echo author of atlc for generating some html versions of man pages. Feel
echo to use it if you update the man pages. Note it relies on having the
echo package man2html, which is available online -its open-source.
nroff -man man/man1/atlc.1 | man2html > docs/html-docs/atlc.1.html
nroff -man man/man1/create_bmp_for_rect_in_rect.1 | man2html > docs/html-docs/create_bmp_for_rect_in_rect.1.html
nroff -man man/man1/create_bmp_for_rect_cen_in_rect.1 | man2html > docs/html-docs/create_bmp_for_rect_cen_in_rect.1.html
nroff -man man/man1/create_bmp_for_circ_in_circ.1 | man2html > docs/html-docs/create_bmp_for_circ_in_circ.1.html
nroff -man man/man1/create_bmp_for_rect_in_circ.1 | man2html > docs/html-docs/create_bmp_for_rect_in_circ.1.html
nroff -man man/man1/create_bmp_for_circ_in_rect.1 | man2html > docs/html-docs/create_bmp_for_circ_in_rect.1.html
nroff -man man/man1/create_bmp_for_symmetrical_stripline.1 | man2html > docs/html-docs/create_bmp_for_symmetrical_stripline.1.html
nroff -man man/man1/create_bmp_for_microstrip_coupler.1    | man2html > docs/html-docs/create_bmp_for_microstrip_coupler.1.html
nroff -man man/man1/create_bmp_for_rect_cen_in_rect_coupler.1 | man2html > docs/html-docs/create_bmp_for_rect_cen_in_rect_coupler.1
nroff -man man/man1/create_bmp_for_stripline_coupler.1 | man2html > docs/html-docs/create_bmp_for_stripline_coupler.1.html
nroff -man man/man1/design_coupler.1 | man2html > docs/html-docs/design_coupler.1.html
nroff -man man/man1/readbin.1 | man2html > docs/html-docs/readbin.1.html
nroff -man man/man1/sysdata.1 | man2html > docs/html-docs/sysdata.1.html
cat header BUGS footer > docs/html-docs/BUGS.html
chmod 644 docs/html-docs/*.html 
chmod 644 man/man1/*.1 README NEWS ChangeLog BUGS COPYING INSTALL THANKS TODO 
chmod 644 README* configure.ac AUTHORS
find . -type d -exec chmod 755 {} \;
