#!/bin/sh
# This programme automatically creates some of the bitmpaps described in
# the documentation. This save a lot of download time, as distributing the
# large files would be difficult. 
# recall the usage for symm_strip is 
# sym_strip W H w filename
# if W is too small, the programme will make it suitable, so we use 1 in
# the following examples. 

# The following are around 25 Ohm transmission lines. 
../src/sym_strip 1 201 668  25-Ohm-201b.bmp
../src/sym_strip 1 401 1334 25-Ohm-401b.bmp

# The following are around 50 Ohm transmission lines. 
../src/sym_strip 1 201 290 50-Ohm-201b.bmp
../src/sym_strip 1 401 578 50-Ohm-401b.bmp

# The following are around 100 Ohm transmission lines. 
../src/sym_strip 1 201 101 100-Ohm-201b.bmp
../src/sym_strip 1 401 202 100-Ohm-401b.bmp

# The following are around 200 Ohm transmission lines. 
../src/sym_strip 1 201 18 200-Ohm-201b.bmp
../src/sym_strip 1 401 36 200-Ohm-401b.bmp
../src/sym_strip 1 801 73 200-Ohm-801b.bmp
# Now create some eccentric cables (off-center coax).
echo eccentric-a.bmp
../src/circ_in_circ 500 400 0 1 > eccentric-a.bmp
echo eccentric-b.bmp
../src/circ_in_circ 500 400 40 1 > eccentric-b.bmp
echo eccentric-c.bmp
../src/circ_in_circ 500 200 0 1 > eccentric-c.bmp
echo eccentric-d.bmp
../src/circ_in_circ 500 200 50 1 > eccentric-d.bmp
echo eccentric-e.bmp
../src/circ_in_circ 500 200 100 1 > eccentric-e.bmp
echo eccentric-f.bmp
../src/circ_in_circ 500 100 0 1 > eccentric-f.bmp
echo eccentric-g.bmp
../src/circ_in_circ 500 100 50 1 > eccentric-g.bmp
echo eccentric-h.bmp
../src/circ_in_circ 500 100 100 1 > eccentric-h.bmp
echo eccentric-i.bmp
../src/circ_in_circ 500  50   0 1 > eccentric-i.bmp
echo eccentric-j.bmp
../src/circ_in_circ 500  50  50 1 > eccentric-j.bmp
echo eccentric-k.bmp
../src/circ_in_circ 500  50 100 1 > eccentric-k.bmp
echo eccentric-l.bmp
../src/circ_in_circ 500  50 150 1 > eccentric-l.bmp
echo eccentric-m.bmp
../src/circ_in_circ 500  50 200 1 > eccentric-m.bmp
echo eccentric-n.bmp
../src/circ_in_circ -b 10 500  50 200 1 > eccentric-n.bmp
../src/sym_strip 1 201 301 wide.bmp
../src/rect_in_rect 268 100 10 40 25 200 100 45 1.0 4.8 > pcb2.bmp
../src/rect_cen_in_rect 268 100 100 50 4.8 > central.bmp 
../src/circ_in_circ 100 30 25 1.006 > off-centre2.bmp
../src/circ_in_rect 20 200 100 50 -5 10.2 > cir.bmp

../src/make_coupler 1.0  1.0 1.0   coupler1.bmp
../src/make_coupler 2.0  1.0 1.0   coupler2.bmp
../src/make_coupler 3.0  1.0 1.0   coupler3.bmp
../src/make_coupler 4.0  1.0 1.0   coupler4.bmp
../src/make_coupler 5.0  1.0 1.0   coupler5.bmp
../src/make_coupler 1.0  1.0 0.5   coupler6.bmp
../src/make_coupler 1.0  1.0 0.1   coupler7.bmp
../src/make_coupler 0.25 1.0 1.0   coupler8.bmp
